Repository nytm/go-grafana-api, pull requests merged in 2020-06, with the labels that each got.

#34 add AlertNotification Uid field
  alertnotification.go
Labels: size/XS

#38 Add method for listing existing dashboards
  dashboard.go
  dashboard_test.go
Labels: size/M

#31 Dashboard tests
  .drone.yml
  admin.go
  dashboard.go
  dashboard_test.go
  datasource_test.go
  folder.go
  mock.go
  org_users.go
  orgs.go
Labels: size/L

#37 Implementation of Team API
  team.go
  teams_test.go
Labels: size/XL

#44 go fmt
  alertnotification_test.go
  dashboard_test.go
  datasource.go
  folder_test.go
  org_users_test.go
  orgs_test.go
  user_test.go
Labels: size/S

#36 Implementation of Folder Permissions API
  folder_permissions.go
  folder_permissions_test.go
Labels: new feature, size/L

#45 Deprecate UID funcs
  dashboard.go
  dashboard_test.go
  datasource.go
Labels: enhancement, size/S

#46 Go version
  .drone.yml
  CODEOWNERS
  go.mod
Labels: size/XS

#51 Centralize request handling
  admin.go
  alertnotification.go
  annotation.go
  client.go
  client_test.go
  dashboard.go
  datasource.go
  folder.go
  folder_permissions.go
  org_users.go
  orgs.go
  playlist.go
  team.go
  user.go
Labels: enhancement, size/XL

#55 Support Alerting API
  admin.go
  admin_test.go
  alert.go
  alert_test.go
Labels: new feature, size/L
